# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github unicom bot

on:
    push:
        branches:
            - master
    schedule:
        - cron: '*/30 4-23 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run app
              run: npm install
            - run: node index.js unicom
              env:
                user: ${{ secrets.user }}
                password: ${{ secrets.password }} 
                appid: ${{ secrets.appid }}
